### PR TITLE
last minute polishing

### PR DESCRIPTION
**Pull request by JedMeister**
3 commits to address 3 issues:

- https://github.com/turnkeylinux/tracker/issues/735#issuecomment-318751003
- https://github.com/turnkeylinux/tracker/issues/735#issuecomment-318769914
- https://github.com/turnkeylinux/tracker/issues/735#issuecomment-318651111

### CODE REVIEW

**Comment by ghost** [comment]
Could be that I am not "savvy" enough with GitHub, but I do not have permissions to push to the polishing branch and integrate my changes with your changes. I did find some minor things that I fixed and merged with my own code. https://github.com/mptmg/ZoneMinder.

Everything worked perfectly when including your changes from this pull request by executing the commands given: (Thanks by the way I would have been looking it up)

```
git remote add jeremy https://github.com/JedMeister/ZoneMinder.git
git fetch jeremy
git checkout -b polishing -t jeremy/14.2-update
```

The things I "fixed" are not of a functional nature, merely cosmetic. Specifically the index.php page referred one to link to Mumble code (my fault must not have edited when using Mumble appliance as template), and rather than using the default shell.png icon for Zoneminder link I resized the logo.png you created and included it in a subfolder "img" in the overlay (var/www/).

I did a quick force update on my repo to align it with the tunkeylinux-apps master for Zoneminder. I also integrated the changes outlined in the polishing branch so I could build and ensure everything is 100% functional including your changes and my changes.

There is probably an infinitely easier way to accomplish getting the changes published, but I am not a GitHub guru by any means. I tried to make life easy for you to merge my changes by allowing you to create a pull request comparing my repo and your repo... comparing the differences and merging the differences.

**Comment by JedMeister** [comment]
Hi @MPTMG,

Sorry perhaps i should have provided a little more detail of what I had in mind. I was in a bit of a rush, plus didn't want to risk offending you with instructions that would be pretty obvious to a git "power user". In future, I'll try to err on the side of giving you a bit more info.

> Could be that I am not "savvy" enough with GitHub, but I do not have permissions to push to the polishing branch and integrate my changes with your changes

I've just taken care of it by "cherry-picking" the 2 commits that you added (but not the one that was just reproducing what I already did). 

For future reference, l meant push the "polishing" branch back to your GH, then open a new pull request.

FWIW, the `-t` switch in the original checkout means that it will follow my `14.2-update` branch. As you don't have write access to that, `git push polishing` failing is to be expected. So if you want to push somewhere else (e.g. your own repo; and create a new `polishing` branch if it doesn't already exist). Assuming that `origin` still points to your GH repo (which I suspect it does, to check: `git remote -v`), you then just need to push explicitly stating where you want to push it to, i.e.:
````
git push origin polishing
````
Then you could have opened a new pull request from your new polishing branch. Because any new commits you made would have been on top of the commits I'd already made (in this PR) then merging your new one would have automatically merged this one.

But it's no issue. Like I say, I just cherry picked your commits. This may be a little too much, but FWIW, I'll show you what I did:

First, I used GH to look at the 3 commits you had added (you can also do that via CLI, but I quite like the GH view). Then I could see that 1 was just replicating the changes I had made, the other 2 were new and I'll want to add them to this PR. I already have your repo added as `mptmg`, so here's what I did:
````
git fetch mptmg # get your updates
git checkout -b mptmg-polish -t mptmg/master # open your master branch locally as mptmg-polishing
git log --oneline -4 # get commit IDs for cherry-pick
git checkout 14.2-update # back to the branch this PR is against
git cherry-pick 4cfe14a # grab the first commit I want from you
git cherry-pick fed0154 # grab the second
git push origin 14.2-update # push everything back to GH
````
And as you can see above, those 2 commits are now part of this PR! :smile: So now I'll merge.

Take care man and don't hesitate to ask questions! I don't always have time to get this involved, but I'm happy to help guide you as much as I can when I have time. :smile:

**Comment by ghost** [comment]
@JedMeister I appreciate the detailed instructions as I am not a git power user by any means. I know you are busy with a lot of things and figured I would just handle it in the method I know I could complete to get the changes published somewhere accessible for you. I have very little experience with contributing to other projects on GitHub, so even with great instructions I would struggle a bit.

Once again I appreciate your assistance getting up to speed on using git. FWIW I was working from a cloned copy of the turnkey-app repo for ZoneMinder, so origin would have been pointing to the wrong place as well in my case. Anyhow this conversation goes in my notes page, so in the future I am better able to assist.

**Comment by JedMeister** [comment]
@MPTMG - no worries, that's fine. FWIW, if you wanted to add your own repo (after cloning from turnkey) that's as simple as this:
````
# if you use SSH auth (my personal preference):
git add my-repo git@github.com:MPTMG/ZoneMinder.git
````
or
````
# if you use HTTPS auth (what GH recommends):
git add my-repo https://github.com/MPTMG/ZoneMinder.git
````

**Pull request merged**
