### PR TITLE
17.2 take2

### LINKED ISSUE #1623: Zoneminder has wrong apache2 config (API not working)
The default apache2 zondeminder.conf (in /etc/apache2/sites-enabled/) is wrong and the API is not working.

In attachment the right file that works

[zoneminder.conf.txt](https://github.com/turnkeylinux/tracker/files/6653631/zoneminder.conf.txt)

```
# Remember to enable cgi mod (i.e. "a2enmod cgi").
ScriptAlias /zm/cgi-bin "/usr/lib/zoneminder/cgi-bin"
<Directory "/usr/lib/zoneminder/cgi-bin">
    Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
    AllowOverride All
    Require all granted
</Directory>


# Order matters. This alias must come first.
Alias /zm/cache /var/cache/zoneminder/cache
<Directory /var/cache/zoneminder/cache>
    Options -Indexes +FollowSymLinks
    AllowOverride None
    <IfModule mod_authz_core.c>
        # Apache 2.4
        Require all granted
    </IfModule>
</Directory>

Alias /zm /usr/share/zoneminder/www
<Directory /usr/share/zoneminder/www>
  Options -Indexes +FollowSymLinks
  <IfModule mod_dir.c>
    DirectoryIndex index.php
  </IfModule>
</Directory>

# For better visibility, the following directives have been migrated from the
# default .htaccess files included with the CakePHP project.
# Parameters not set here are inherited from the parent directive above.
<Directory "/usr/share/zoneminder/www/api">
   RewriteEngine on
   RewriteRule ^$ app/webroot/ [L]
   RewriteRule (.*) app/webroot/$1 [L]
   RewriteBase /zm/api
</Directory>

<Directory "/usr/share/zoneminder/www/api/app">
   RewriteEngine on
   RewriteRule ^$ webroot/ [L]
   RewriteRule (.*) webroot/$1 [L]
   RewriteBase /zm/api
</Directory>

<Directory "/usr/share/zoneminder/www/api/app/webroot">
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
    RewriteBase /zm/api
</Directory>
```

### LINKED ISSUE #1791: Zoneminder 1.34 has long been deprecated. Has multiple CVEs.  Upgrade to 1.36 series.

### PR DESCRIPTION
**Pull request by JedMeister**
Update Zoneminder to install v1.36.x from upstream zmrepo apt repo.

closes https://github.com/turnkeylinux/tracker/issues/1791

At the time of writing the current version is v1.36.32, but I have it on a good authority that v1.36.33 is very close. That should only require a changelog tweak though AFAIK.

----

This update also includes new Apache conf created from the example provided by the package.

closes https://github.com/turnkeylinux/tracker/issues/1623

### CODE REVIEW

**Review by OnGle — APPROVED** [review]
lgtm!

**Review by Christie018 — APPROVED** [review]
The code changes update the zoneminder and its download source. Code changes also fix the bug with the API and close related tracker issues. Lastly, all code changes have been documented in the appliance changelog so I don't have any issues merging this.

**Comment by jimmystewart** [comment]
Trying to update from 1.34.x to the new 1.36.x as instructed by using the command "apt-get update" but I get the following errors:

root@zoneminder ~# apt-get update
Hit:1 http://security.debian.org buster/updates InRelease
Hit:2 http://download.zerotier.com/debian/buster buster InRelease
Hit:3 http://deb.debian.org/debian buster InRelease
Ign:4 http://archive.turnkeylinux.org/debian buster-security InRelease
Ign:5 http://archive.turnkeylinux.org/debian buster InRelease
Ign:6 http://zmrepo.zoneminder.com/debian/release-1.34 buster/ InRelease
Hit:7 http://archive.turnkeylinux.org/debian buster-security Release
Get:9 http://zmrepo.zoneminder.com/debian/release-1.34 buster/ Release [1387 B]
Hit:10 http://archive.turnkeylinux.org/debian buster Release
Get:11 http://zmrepo.zoneminder.com/debian/release-1.34 buster/ Release.gpg [862 B]
Err:11 http://zmrepo.zoneminder.com/debian/release-1.34 buster/ Release.gpg
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8C670C86F88B031
Fetched 2249 B in 0s (4604 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://zmrepo.zoneminder.com/debian/release-1.34 buster/ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8C670C86F88B031
W: Failed to fetch http://zmrepo.zoneminder.com/debian/release-1.34/buster/Release.gpg  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8C670C86F88B031
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by JedMeister** [comment]
Hi @jimmystewart - FWIW we generally do support over on our [forums](https://www.turnkeylinux.org/forum/support/) (requires free website user account). We generally reserve GitHub for (consolidated) [bug tracking](https://github.com/turnkeylinux/tracker/issues/) and code development. In future, please post in the forums instead.

Regardless, seeing as you're here now, the issue you're having is 2 fold. Firstly you need to update the repository signing key. Plus you also need to update the repository to use the v1.36.x branch.

Probably the easiest way to go is to just overwrite the existing ones (this assumes you're running as root, if not then precede these commands with `sudo su`:

```
cat > /etc/apt/preferences.d/zoneminder.pref <<EOF
Package: *
Pin: origin zmrepo.zoneminder.com
Pin-Priority: 10

Explanation: Pin ZoneMinder from 3rd party repos
Package: zoneminder
Pin: origin zmrepo.zoneminder.com
Pin-Priority: 500
EOF

cat > /etc/apt/sources.list.d/zoneminder.list <<EOF
# ZoneMinder offical apt repo
deb [signed-by=/usr/share/keyrings/zoneminder.gpg] http://zmrepo.zoneminder.com/debian/release-1.36 buster/
EOF
```
Then you just need to update the key file:
```
curl https://zmrepo.zoneminder.com/debian/archive-keyring.gpg | gpg --dearmor > /usr/share/keyrings/zoneminder.gpg
rm archive-keyring.gpg
```
Then you should be able to update to the v1.36.x version like this:
```
apt update
apt install zoneminder
```

**Pull request merged**
